name: peregrine_app_taha
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  http: ^1.0.0
  logger: ^2.0.2
  lucide_icons: ^0.257.0
  intl: ^0.19.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/logo1.png
    - assets/images/logo.png

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF" # Background color for Android adaptive icons
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true
